# Mongo-Sync Configurations

local:
  db: 'test'
  host:
    url: 'localhost'
    port: 27017
  access:
    username: 'user'
    password: '*****'
  tunnel:
    on: false
    username: 'remote_ssh_user'
    port: 22

dev:
  db: 'test'
  host:
    url: '10.20.1.22'
    port: 27017
  access:
    username: 'user'
    password: '*****'
  tunnel:
    on: false
    username: 'remote_ssh_user'
    port: 22

prod:
  db: 'test'
  host:
    url: '10.20.1.23'
    port: 27019
  access:
    username: 'user'
    password: '*****'
  tunnel:
    on: false
    username: 'remote_ssh_user'
    port: 22
# All of the parameters above are required,
# without them, the script will fail
