# Mongo-Sync Configurations

local:
  db: 'test'
  host:
    url: 'localhost'
    port: 27017
  access:
    username: 'root'
    password: 'easo336'
  tunnel:
    on: false
    username: 'remote_ssh_user'
    port: 22

dev:
  db: 'payloadcms'
  host:
    url: '10.20.1.22'
    port: 27017
  access:
    username: 'ESGReadWrite'
    password: '2bq3qrtxzJdF'
  tunnel:
    on: false
    username: 'remote_ssh_user'
    port: 22

prod:
  db: 'payloadcms'
  host:
    url: '10.20.1.22'
    port: 27019
  access:
    username: 'MongoDBReadWrite'
    password: 'd5aaefb12e46b3791099db8b88892252'
  tunnel:
    on: false
    username: 'remote_ssh_user'
    port: 22
# All of the parameters above are required,
# without them, the script will fail
